name: Pytest

on:
  push:
    branches: [ main ]
    paths: [ "**.py", ".github/workflows/pytest.yml" ]
  pull_request:
    branches: [ main ]
    paths: [ "**.py", ".github/workflows/pytest.yml" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv sync --dev
      - run: uv run pytest --cov=src
